### ISSUE TITLE
add resource page for LBRY api wrappers

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#123] opened 2018-07-12 21:00 UTC
Thought lbry.tech would be a good place to keep track of lbry/community maintained api wrappers. Currently we have the [php-api wrapper](https://github.com/lbryio/php-api) and [Ruby Gem](https://rubygems.org/gems/lbry) / [Ruby Github](https://github.com/dan1d/lbry-api-ruby)

**Comment by kauffj** [comment] 2018-07-12 21:48
Definitely!

**Comment by alyssaoc** [comment] 2018-07-26 15:49
This is a duplicate of #117  and will be closed

**Comment by tzarebczan** [comment] 2018-08-31 02:35
completed in https://github.com/lbryio/lbry.tech/pull/137

**Closed** 2018-08-31 02:36 UTC
Labels: Content, area: docs, needs: grooming, type: discussion
